### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by kneasle** [kneasle/ringing#46]
## Monument (CLI/lib)

- [ ] Sort comps by music?
- [ ] Add `bob_only` and `single_only`
- [ ] Improve error messages
- [ ] Default music scoring
- [ ] Create benchmark suite
- [ ] Graph optimisations
  - [ ] Remove links between mutually false nodes
  - [ ] Merge nodes which must be adjacent
  - [ ] Allow graph optimisation to fork and produce multiple graphs
  - [ ] Make the point of graph optimisation to minimise `(#nodes, #links, #falseness)`

## BellFrame

- [ ] Switch to making `Bell`/`Stage`/etc. be newtypes over `u8` (reducing memory usage, better cache performance, potential for SIMD)
- [ ] Make `Row::closure{from_rounds}` return an `Iterator` rather than a `Vec`
- [ ] Remove `type Block = AnnotBlock<()>` and rename `AnnotBlock` to `Block`
- [ ] More test coverage
- [ ] More docs/examples coverage
- [ ] Fix unsoundness issues:
  - [ ] Check `Mask` invariants
  - [ ] Give `Regex`s a `Stage`
- [ ] Do we ever need to parse things without knowing stage?
